config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'root#index'

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    namespace :app do
      resources :dashboard, only: %i[index]

      # everything is not prefixed with /user_space
      scope module: :user_space, as: :user_space do
        # so this would be /app/order
        resources :order, except: %i[destroy]
        get 'order_datatable' => 'order#datatable'
      end

      scope path: :market, module: :market_space, as: :market_space do
        resources :market

        resources :product do
          get 'orders_datatable'
        end
        get 'product_datatable' => 'product#datatable'

        resources :user, except: %i[edit destroy] do
          get 'permissions'
          get 'remove'
          match 'remove' => 'user#remove_from_market', via: %i[post patch put delete]
        end
        get 'user_datatable' => 'user#datatable'
        get 'invite_user_to_market' => 'user#invite_user_to_market_view'
        match 'invite_user_to_market' => 'user#invite_user_to_market', via: %i[post patch put]

        resources :receiving do
          get 'line_item/:receive_item' => 'receiving#receiving_item_line', as: :item_line
        end
        get 'receiving_datatable' => 'receiving#datatable'

        resources :order, except: :destroy
        get 'order_datatable' => 'order#datatable'

        resources :customer, except: %i[edit update destroy] do
          get 'orders_datatable'
        end
        get 'customer_datatable' => 'customer#datatable'
      end

      get 'action_logs' => 'action_logs#datatable', as: :action_logs_datatable

      namespace :site_admin do
        resources :user
        get 'user_datatable' => 'user#datatable'
        resources :market
        get 'market_datatable' => 'market#datatable'

        # sidekiq
        authenticate :user, ->(user) { user.site_admin } do
          mount Sidekiq::Web => '/sidekiq'
        end

        scope :settings, as: :settings do
          get '/' => 'settings#edit'
          match '/' => 'settings#update', via: %i[post patch put]
        end
      end
      get '/site_admin' => 'site_admin#index'
    end

    get '/app' => 'app#index'
    match '/app/set_market' => 'app#set_market', via: %i[post put patch]

    # everything under this scope is NOT prefixed with /site
    scope module: :site do
      resources :product, only: %i[index show]

      scope :cart, as: :cart do
        get '' => 'cart#index'
        get 'navbar' => 'cart#navbar'
        match 'update_item' => 'cart#update_item', via: %i[post patch put]
        match 'update_cart' => 'cart#update_cart', via: %i[post patch put]
      end
    end
  end

  # API
  namespace :api, defaults: { format: :json } do
    namespace :webhook do
    end
  end

  # shortcuts
  get '/l', to: redirect('/users/sign_in')
  get '/login', to: redirect('/users/sign_in')
end

app/controllers/app/market_space/customer_controller.rb
# frozen_string_literal: true

module App
  module MarketSpace
    # market customers
    class CustomerController < MarketSpaceController
      before_action :find_customer, except: %i[index create datatable]

      def index
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_CUSTOMERS, @current_market)
      end

      def show
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_CUSTOMERS, @current_market)
      end

      def datatable
        return render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_CUSTOMERS, @current_market)

        requested_length = params[:length].to_i
        requested_start  = params[:start].to_i

        sort_col = params['order']['0']['column'] # eg 0 for column 0
        sort_dir = params['order']['0']['dir'] # 'desc' or 'asc'
        sort_name = params['columns'][sort_col]['name'].to_s # the column name set in the data table initialization. MUST equal the DB column name
        search_value = params['search']['value']

        return unless %w[id email created_at].include? sort_name

        filtered_count = @current_market.customers.where(real: true).size
        records = @current_market.customers
                                 .where(real: true)
                                 .order(sort_name => sort_dir)
                                 .select(:id, :email, :created_at)
                                 .limit(requested_length)
                                 .offset(requested_start)

        ActiveRecord::Base.include_root_in_json = false

        payload = {
          draw: params[:draw],
          recordsTotal: @current_market.customers.size,
          recordsFiltered: filtered_count,
          data: records
        }

        render json: payload, status: :ok
      end

      def orders_datatable
        return render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_CUSTOMERS, @current_market)

        requested_length = params[:length].to_i
        requested_start  = params[:start].to_i

        sort_col = params['order']['0']['column'] # eg 0 for column 0
        sort_dir = params['order']['0']['dir'] # 'desc' or 'asc'
        sort_name = params['columns'][sort_col]['name'].to_s # the column name set in the data table initialization. MUST equal the DB column name
        search_value = params['search']['value']

        return unless %w[orders.created_at orders.payment_status orders.status].include? sort_name

        column_select = %w[orders.id orders.created_at orders.payment_status orders.status COUNT(order_items.order_id)].freeze
        group_select = %w[orders.id order_items.order_id].freeze

        filtered_count = @customer.orders.size
        records = @customer.orders
                           .left_joins(:order_items)
                           .order(sort_name => sort_dir)
                           .select(column_select)
                           .group(group_select)
                           .limit(requested_length)
                           .offset(requested_start)

        ActiveRecord::Base.include_root_in_json = false

        payload = {
          draw: params[:draw],
          recordsTotal: @customer.orders.size,
          recordsFiltered: filtered_count,
          data: records
        }

        render json: payload, status: :ok
      end

      private

      def find_customer
        @customer = if !params[:id].nil?
                      @current_market.customers.find_by(id: params[:id])
                    else
                      @current_market.customers.find_by(id: params[:customer_id])
                    end
      end
    end
  end
end

app/controllers/app/market_space/market_controller.rb
# frozen_string_literal: true

module App
  module MarketSpace
    # Handles user facing market stuff
    class MarketController < MarketSpaceController
      before_action :find_market, except: %i[index datatable new create]
      skip_before_action :current_market, :get_user_market_permissions, :require_market, only: %i[new create]

      def new
        @market = Market.new
      end

      def create
        safe_params = params.require(:create).permit(:display_name, :path_name, :email, :stripe_publishable_key, :stripe_secret_key, :default_currency, :stripe_webhook_secret)

        @market = Market.new safe_params

        if @market.invalid?
          return respond_to do |format|
            format.html { render :new, status: :unprocessable_entity }
          end
        end

        @market.save

        current_user.user_market_permissions.create(
          market_id: @market.id,
          formatted_permissions: UserMarketPermission.format_permissions([UserMarketPermission::OWNER])
        )

        redirect_to app_market_space_market_path @market
      end

      def show
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::OWNER, @market)
      end

      def edit
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::OWNER, @market)
      end

      def update
        return render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::OWNER, @market)

        # normally I'd do safe params but in this case params are generated on the fly, so no can do.

        # example params:
        # Parameters: {"authenticity_token"=>"[FILTERED]", "update"=>{"display_name"=>"Dalen's Market", "email"=>"cloud@m6securities.com", "default_currency"=>"USD", "payment_gateways"=>[{"name"=>"Stripe", "gateway"=>"stripe", "stripe"=>{"publishable_key"=>"[FILTERED]", "secret_key"=>"[FILTERED]"}}]}, "locale"=>"en", "id"=>"750858574031683585"}

        display_name = params[:update][:display_name]
        email = params[:update][:email]
        default_currency = params[:update][:default_currency]
        payment_gateways = params[:update][:payment_gateways]

        @market.assign_attributes(display_name:, email:, default_currency:)

        # now update the payment gateways
        # we need to make sure that the array that was submitted matches the array that is in the db
        # if a record isn't submitted but in the db, then we delete it
        # if a submitted record has valid credentials, then we update it
        # if a submitted record has invalid credentials, then we do nothing
        # if a submitted record has no credentials, then we do nothing
        # credentials need to match PaymentGateway::GATEWAY_CONFIG

        # if no payment gateways are submitted, then we delete all of them, and disable the market
        if payment_gateways.nil?
          @market.payment_gateways.destroy_all
          @market.update(enabled: false)
          @market.payment_gateways.reload

          flash[:success] = 'Market updated' if @market.save

          return render :edit
        end

        payment_gateways.each do |payment_gateway|
          # find the record in the db
          db_payment_gateway = @market.payment_gateways.find_by(gateway: payment_gateway[:gateway])

          # check to see if the gateway exists
          new_gateway = false
          if db_payment_gateway.nil?
            # if the gateway doesn't exist, then we need to create it
            db_payment_gateway = @market.payment_gateways.new(gateway: payment_gateway[:gateway])
          end

          # check to see if the credentials are valid
          gateway_creds = payment_gateway["#{payment_gateway[:gateway]}"]

          # compare the keys to GateWayConfig
          valid_creds = true
          PaymentGateway::GATEWAY_CONFIG[payment_gateway[:gateway].to_sym].each do |key|
            if gateway_creds.blank?
              valid_creds = false
              break
            end

            if gateway_creds[key].blank?
              valid_creds = false
              break
            end
          end

          unless valid_creds
            # if the credentials are invalid, then we do nothing. if it's a new gateway, then we delete it
            db_payment_gateway.destroy if new_gateway
            next
          end

          # if the credentials are valid, then we update the record
          db_payment_gateway.assign_attributes(credentials: gateway_creds)

          # check to see if the db_payment_gateway is valid. If not, then let the user now
          flash[:error] = db_payment_gateway.errors.full_messages.join(', ') unless db_payment_gateway.valid?

          # if the db_payment_gateway is valid, then we save it
          db_payment_gateway.save
        end

        # now we remove deleted payment gateways

        @market.payment_gateways.each do |payment_gateway|
          payment_gateway.destroy unless payment_gateways.any? { |pg| pg[:gateway] == payment_gateway.gateway }
        end

        @market.payment_gateways.reload

        flash[:success] = 'Market updated' if @market.save

        render :edit
      end

      private

      def find_market
        puts 'Finding Market'
        @market = Market.find_by id: params[:id]
      end
    end
  end
end

app/controllers/app/market_space/order_controller.rb
# frozen_string_literal: true

module App
  module MarketSpace
    # handles orders on the market side
    class OrderController < MarketSpaceController
      before_action :require_market
      before_action :find_order, only: %i[show edit update]

      def index
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_ORDERS, @current_market)
      end

      def show
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_ORDERS, @current_market)
      end

      def update
        return render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::EDIT_ORDERS, @current_market)

        safe_params = params.require(:update).permit(:status)

        # @order.status = safe_params[:status]

        if log_model_updates(%i[status], @order, safe_params, @user_market_permissions)
          flash[:success] = 'Order status updated'
          render :edit
        else
          flash[:error] = 'Order status could not be updated'
          render :edit, status: :unprocessable_entity
        end
      end

      def datatable
        requested_length = params[:length].to_i
        requested_start  = params[:start].to_i

        sort_col = params['order']['0']['column'] # eg 0 for column 0
        sort_dir = params['order']['0']['dir'] # 'desc' or 'asc'
        sort_name = params['columns'][sort_col]['name'].to_s # the column name set in the data table initialization. MUST equal the DB column name
        search_value = params['search']['value']

        return unless %w[orders.created_at orders.payment_status orders.status orders.total_price_cents].include? sort_name

        column_select = %w[orders.id orders.created_at orders.payment_status orders.status COUNT(order_items.order_id) orders.total_price_cents orders.total_price_currency].freeze
        group_select = %w[orders.id order_items.order_id].freeze

        filtered_count = @current_market.orders.size
        records = @current_market.orders.left_joins(:order_items)
                                 .order(sort_name => sort_dir)
                                 .select(column_select)
                                 .group(group_select)
                                 .limit(requested_length)
                                 .offset(requested_start)

        ActiveRecord::Base.include_root_in_json = false

        data = []

        records.each do |record|
          hash = record.as_json
          hash['total_price'] = record.total_price.format unless record.total_price_cents.nil? || record.total_price_currency.nil?

          data << hash
        end

        payload = {
          draw: params[:draw],
          recordsTotal: @current_market.orders.size,
          recordsFiltered: filtered_count,
          data:
        }

        render json: payload, status: :ok
      end

      private

      def find_order
        @order = @current_market.orders.find_by(id: params[:id])
        render 'error/not_found', status: :not_found, layout: 'error' unless @order
      end
    end
  end
end

app/controllers/app/market_space_controller.rb
# frozen_string_literal: true

module App
  class MarketSpaceController < AppController
    before_action :require_market
    before_action :current_market
    before_action :get_user_market_permissions
    before_action :create_market_if_not_exist
    before_action :set_market_dropdown_true

    private

    def create_market_if_not_exist
      redirect_to new_app_market_space_market_path if @current_market.nil?
    end
  end
end

app/helpers/app/market_space/customer_helper.rb
module App::MarketSpace::CustomerHelper
end

app/helpers/app/market_space/market_helper.rb
module App::MarketSpace::MarketHelper
end

app/helpers/app/market_space/order_helper.rb
module App::MarketSpace::OrderHelper
end

app/helpers/app/market_space/product_helper.rb
module App::MarketSpace::ProductHelper
end

app/helpers/app/market_space/receiving_helper.rb
module App::MarketSpace::ReceivingHelper
end

app/helpers/app/market_space/user_helper.rb
module App::MarketSpace::UserHelper
end

app/helpers/app/market_space_helper.rb
module App::MarketSpaceHelper
end

app/helpers/app/site_admin/user_helper.rb
module App::SiteAdmin::UserHelper
end

app/views/app/market_space/user/index.html.erb
<!-- display a datatable of all markets -->
<% content_for :title, 'Users' %>

<div class="content-header d-flex mb-1 justify-content-between">
  <h1 class="m-0" style="line-height: 39px;">
    Users
  </h1>
</div>

<div class="mb-2">
  <%= turbo_frame_tag :invite_user, src: app_market_space_invite_user_to_market_path, loading: :lazy do %>
    <% render SpinnerComponent.new, cached: true %>
  <% end %>
</div>

<div class="card">
  <div class="card-content">
    <div class="card-body">

      <table id="products-table" class="table table-striped" style="width:100%"
             data-controller="app--market-space--user--index"
             data-app--market-space--user--index-url-value="<%= app_market_space_user_datatable_path %>"
             data-app--market-space--user--index-item-path-value="<%= app_market_space_user_index_path %>"
      >
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Last Activity At</th>
          <th>View</th>
        </tr>
        </thead>

        <tbody class="table-striped"></tbody>

        <tfoot>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Last Activity At</th>
          <th>View</th>
        </tr>
        </tfoot>
      </table>

    </div>
  </div>
</div>

app/views/app/market_space/user/invite_user_to_market_view.html+turbo_frame.erb
<%= turbo_frame_tag :invite_user do %>
  <div class="card">
    <div class="card-body">

      <%= render FormFlashComponent.new %>

      <div>
        <%= render(FormErrorComponent.new(@permission.errors.messages)) unless @permission.nil? %>
      </div>

      <form action="<%= app_market_space_invite_user_to_market_path %>" method="post">
        <div class="d-flex justify-content-between">
          <%= render InputBlockComponent.new(title: "Invite User to Market", name: 'invite[email]', type: :email, value: @email, placeholder: 'john.smith@example.com', div_classes: "me-2 w-100"), cached: true %>
          <div class="d-flex flex-column justify-content-end">
            <button type="submit" class="btn btn-outline-success mb-0">Invite</button>
          </div>
        </div>
      </form>
    </div>
  </div>
<% end %>

app/views/app/market_space/user/invite_user_to_market_view.html.erb
<% content_for :title, "Invite User to Market" %>

<%= turbo_frame_tag :invite_user, src: app_market_space_invite_user_to_market_path, loading: :lazy do %>
  <%= render SpinnerComponent.new, cached: true %>
<% end %>

app/views/app/market_space/user/permissions.html+turbo_frame.erb
<%= turbo_frame_tag "user_#{@user.id}_permissions" do %>
  <form action="<%= app_market_space_user_path @user %>" method="patch">
    <div class="card">
      <div class="card-body">

        <h3 class="card-title">
          <i data-feather='user-check'></i>
          Permissions
        </h3>

        <% if @user_market_permissions.nil? %>
          <% flash[:error] = 'User does not belong to this market' %>
        <% else %>
          <%= render FormErrorComponent.new(@user_market_permissions.errors.messages) %>
        <% end %>

        <%= render FormFlashComponent.new %>

        <hr>

        <div class="d-flex justify-content-start">
          <!-- owner -->
          <%= render SwitchBlockComponent.new(title: 'Owner', name: 'update[owner]', checked: @user.permission?(UserMarketPermission::OWNER, @current_market)) %>
          <!-- admin -->
          <%= render SwitchBlockComponent.new(title: 'Admin', name: 'update[admin]', checked: @user.permission?(UserMarketPermission::ADMIN, @current_market), div_classes: "#{SwitchBlockComponent::DEFAULT_DIV_CLASSES} mx-2") %>
        </div>

        <div class="d-flex justify-content-between">
          <%= render SwitchBlockComponent.new(title: 'View Products', name: 'update[view_products]', checked: @user.permission?(UserMarketPermission::VIEW_PRODUCTS, @current_market)) %>
          <!-- edit products -->
          <%= render SwitchBlockComponent.new(title: 'Edit Products', name: 'update[edit_products]', checked: @user.permission?(UserMarketPermission::EDIT_PRODUCTS, @current_market)) %>
        </div>

        <button type="submit" class="btn btn-primary w-100">
          <i data-feather='save'></i>
          Save
        </button>

      </div>
    </div>
  </form>
<% end %>

app/views/app/market_space/user/remove.html+turbo_frame.erb
<%= turbo_frame_tag "user_#{@user.id}_remove" do %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Remove User</h5>

      <%= render FormFlashComponent.new %>

      <form action="<%= app_market_space_user_remove_path(@user) %>" method="delete">
        <button type="submit" class="btn btn-danger w-100">
          <i data-feather="trash"></i>
          Remove from Market
        </button>
      </form>
    </div>
  </div>
<% end %>

app/views/app/market_space/user/show.html+turbo_frame.erb
<%= turbo_frame_tag @user, target: '_top' do %>
  <div class="d-flex justify-content-between mb-2">
    <div>
      <h1>
        User: <%= @user.email %>
      </h1>
    </div>
  </div>

  <div class="row">

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <!-- details card -->
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
            Details
          </h5>

          <hr>

          <p class="card-text">
            <b>Display Name:</b> <%= @user.display_name %>
          </p>

          <p class="card-text">
            <b>Email:</b>
            <a href="mailto:<%= @user.email %>">
              <i data-feather="mail"></i> <%= @user.email %>
            </a>
          </p>

          <p class="card-text">
            <b>Added to Market:</b> <%= @user_market_permissions.created_at %>
          </p>

          <!-- last sign in at -->
          <p class="card-text">
            <b>Last Sign In:</b> <%= @user.last_sign_in_at %>
          </p>

          <!-- last activity at -->
          <p class="card-text">
            <b>Last Activity:</b> <%= @user.last_activity_at %>
          </p>

        </div>
      </div>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
      <%= turbo_frame_tag "user_#{@user.id}_permissions", src: app_market_space_user_permissions_path(@user), loading: :lazy do %>
        <%= render SpinnerComponent.new, cached: true %>
      <% end %>

      <br>

      <%= turbo_frame_tag "user_#{@user.id}_remove", src: app_market_space_user_remove_path(@user), loading: :lazy do %>
        <%= render SpinnerComponent.new, cached: true %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/app/market_space/user/show.html.erb
<% content_for :title, "User #{@user.email}" %>

<%= turbo_frame_tag @user, src: app_market_space_user_path(@user), loading: :lazy, target: '_top' do %>
  <%= render SpinnerComponent.new, cached: true %>
<% end %>