config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'root#index'

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    namespace :app do
      resources :dashboard, only: %i[index]

      # everything is not prefixed with /user_space
      scope module: :user_space, as: :user_space do
        # so this would be /app/order
        resources :order, except: %i[destroy]
        get 'order_datatable' => 'order#datatable'
      end

      scope path: :market, module: :market_space, as: :market_space do
        resources :market

        resources :product do
          get 'orders_datatable'
        end
        get 'product_datatable' => 'product#datatable'

        resources :user, except: %i[edit destroy] do
          get 'permissions'
          get 'remove'
          match 'remove' => 'user#remove_from_market', via: %i[post patch put delete]
        end
        get 'user_datatable' => 'user#datatable'
        get 'invite_user_to_market' => 'user#invite_user_to_market_view'
        match 'invite_user_to_market' => 'user#invite_user_to_market', via: %i[post patch put]

        resources :receiving do
          get 'line_item/:receive_item' => 'receiving#receiving_item_line', as: :item_line
        end
        get 'receiving_datatable' => 'receiving#datatable'

        resources :order, except: :destroy
        get 'order_datatable' => 'order#datatable'

        resources :customer, except: %i[edit update destroy] do
          get 'orders_datatable'
        end
        get 'customer_datatable' => 'customer#datatable'
      end

      get 'action_logs' => 'action_logs#datatable', as: :action_logs_datatable

      namespace :site_admin do
        resources :user
        get 'user_datatable' => 'user#datatable'
        resources :market
        get 'market_datatable' => 'market#datatable'

        # sidekiq
        authenticate :user, ->(user) { user.site_admin } do
          mount Sidekiq::Web => '/sidekiq'
        end

        scope :settings, as: :settings do
          get '/' => 'settings#edit'
          match '/' => 'settings#update', via: %i[post patch put]
        end
      end
      get '/site_admin' => 'site_admin#index'
    end

    get '/app' => 'app#index'
    match '/app/set_market' => 'app#set_market', via: %i[post put patch]

    # everything under this scope is NOT prefixed with /site
    scope module: :site do
      resources :product, only: %i[index show]

      scope :cart, as: :cart do
        get '' => 'cart#index'
        get 'navbar' => 'cart#navbar'
        match 'update_item' => 'cart#update_item', via: %i[post patch put]
        match 'update_cart' => 'cart#update_cart', via: %i[post patch put]
      end
    end
  end

  # API
  namespace :api, defaults: { format: :json } do
    namespace :webhook do
    end
  end

  # shortcuts
  get '/l', to: redirect('/users/sign_in')
  get '/login', to: redirect('/users/sign_in')
end

app/models/order.rb
# frozen_string_literal: true

#
# Represents a single order with a single payment, tied to a customer.
class Order < ApplicationRecord
  # Constants
  # --------------------------------------------------------------------------------------------------------------------

  # Payment Status
  PS_NONE = 0 # When the order is created, but no payment has been attempted.
  PS_REQUIRES_PAYMENT_METHOD = 1
  PS_REQUIRES_CONFIRMATION = 2
  PS_REQUIRES_ACTION = 3
  PS_PROCESSING = 4
  PS_REQUIRES_CAPTURE = 5
  PS_CANCELLED = 6
  PS_SUCCEEDED = 7

  enum :payment_status, {
    none: PS_NONE,
    requires_payment_method: PS_REQUIRES_PAYMENT_METHOD,
    requires_confirmation: PS_REQUIRES_CONFIRMATION,
    requires_action: PS_REQUIRES_ACTION,
    processing: PS_PROCESSING,
    requires_capture: PS_REQUIRES_CAPTURE,
    cancelled: PS_CANCELLED,
    succeeded: PS_SUCCEEDED
  }, prefix: true, default: :payment_status_none # ignore the warning this is right

  PS_ARRAY = [
    PS_NONE,
    PS_REQUIRES_PAYMENT_METHOD,
    PS_REQUIRES_CONFIRMATION,
    PS_REQUIRES_ACTION,
    PS_PROCESSING,
    PS_REQUIRES_CAPTURE,
    PS_CANCELLED,
    PS_SUCCEEDED
  ].freeze

  PS_OPTIONS_ARRAY = [
    ['None', PS_NONE],
    ['Requires Payment Method', PS_REQUIRES_PAYMENT_METHOD],
    ['Requires Confirmation', PS_REQUIRES_CONFIRMATION],
    ['Requires Action', PS_REQUIRES_ACTION],
    ['Processing', PS_PROCESSING],
    ['Requires Capture', PS_REQUIRES_CAPTURE],
    ['Canceled', PS_CANCELLED],
    ['Succeeded', PS_SUCCEEDED]
  ].freeze

  # Order Status
  OS_NOT_ACKNOWLEDGED = 0
  OS_ACKNOWLEDGED = 1
  OS_PROCESSING = 2
  OS_SHIPPED = 3
  OS_DELIVERED = 4
  OS_CANCELLED = 5

  enum :status, {
    not_acknowledged: OS_NOT_ACKNOWLEDGED,
    acknowledged: OS_ACKNOWLEDGED,
    processing: OS_PROCESSING,
    shipped: OS_SHIPPED,
    delivered: OS_DELIVERED,
    cancelled: OS_CANCELLED
  }, prefix: :status # ignore the warning this is right

  OS_ARRAY = [
    OS_NOT_ACKNOWLEDGED,
    OS_ACKNOWLEDGED,
    OS_PROCESSING,
    OS_SHIPPED,
    OS_DELIVERED,
    OS_CANCELLED
  ].freeze

  OS_OPTIONS_ARRAY = [
    ['Waiting Acknowledgement', OS_NOT_ACKNOWLEDGED],
    ['Acknowledged', OS_ACKNOWLEDGED],
    ['Processing', OS_PROCESSING],
    ['Shipped', OS_SHIPPED],
    ['Delivered', OS_DELIVERED],
    ['Cancelled', OS_CANCELLED]
  ].freeze

  # Associations
  # --------------------------------------------------------------------------------------------------------------------
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :action_logs, as: :loggable, dependent: :destroy
  has_one :address, as: :addressable, dependent: :destroy

  # Validations
  # --------------------------------------------------------------------------------------------------------------------
  validates_presence_of :customer
  validates_presence_of :address
  # validates :payment_status, inclusion: { in: PS_ARRAY }
  validates :status, inclusion: { in: statuses.keys }

  # Methods
  # --------------------------------------------------------------------------------------------------------------------

  monetize :total_price_cents, allow_nil: true

  def market
    customer.market
  end

  def user
    customer.user
  end
end

app/controllers/app/market_space/order_controller.rb
# frozen_string_literal: true

module App
  module MarketSpace
    # handles orders on the market side
    class OrderController < MarketSpaceController
      before_action :require_market
      before_action :find_order, only: %i[show edit update]

      def index
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_ORDERS, @current_market)
      end

      def show
        render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::VIEW_ORDERS, @current_market)
      end

      def update
        return render 'error/unauthorized', status: :unauthorized, layout: 'error' unless current_user.permission?(UserMarketPermission::EDIT_ORDERS, @current_market)

        safe_params = params.require(:update).permit(:status)

        # @order.status = safe_params[:status]

        if log_model_updates(%i[status], @order, safe_params, @user_market_permissions)
          flash[:success] = 'Order status updated'
          render :edit
        else
          flash[:error] = 'Order status could not be updated'
          render :edit, status: :unprocessable_entity
        end
      end

      def datatable
        requested_length = params[:length].to_i
        requested_start  = params[:start].to_i

        sort_col = params['order']['0']['column'] # eg 0 for column 0
        sort_dir = params['order']['0']['dir'] # 'desc' or 'asc'
        sort_name = params['columns'][sort_col]['name'].to_s # the column name set in the data table initialization. MUST equal the DB column name
        search_value = params['search']['value']

        return unless %w[orders.created_at orders.payment_status orders.status orders.total_price_cents].include? sort_name

        column_select = %w[orders.id orders.created_at orders.payment_status orders.status COUNT(order_items.order_id) orders.total_price_cents orders.total_price_currency].freeze
        group_select = %w[orders.id order_items.order_id].freeze

        filtered_count = @current_market.orders.size
        records = @current_market.orders.left_joins(:order_items)
                                 .order(sort_name => sort_dir)
                                 .select(column_select)
                                 .group(group_select)
                                 .limit(requested_length)
                                 .offset(requested_start)

        ActiveRecord::Base.include_root_in_json = false

        data = []

        records.each do |record|
          hash = record.as_json
          hash['total_price'] = record.total_price.format unless record.total_price_cents.nil? || record.total_price_currency.nil?

          data << hash
        end

        payload = {
          draw: params[:draw],
          recordsTotal: @current_market.orders.size,
          recordsFiltered: filtered_count,
          data:
        }

        render json: payload, status: :ok
      end

      private

      def find_order
        @order = @current_market.orders.find_by(id: params[:id])
        render 'error/not_found', status: :not_found, layout: 'error' unless @order
      end
    end
  end
end

app/controllers/app/user_space/order_controller.rb
# frozen_string_literal: true

module App
  module UserSpace
    class OrderController < UserSpaceController
      before_action :find_order, except: %i[index new create datatable]

      def datatable
        requested_length = params[:length].to_i
        requested_start  = params[:start].to_i

        sort_col = params['order']['0']['column'] # eg 0 for column 0
        sort_dir = params['order']['0']['dir'] # 'desc' or 'asc'
        sort_name = params['columns'][sort_col]['name'].to_s # the column name set in the data table initialization. MUST equal the DB column name
        search_value = params['search']['value']

        return unless %w[orders.created_at orders.status orders.total_price_cents].include? sort_name

        column_select = %w[orders.id orders.created_at orders.status COUNT(order_items.order_id) orders.total_price_cents orders.total_price_currency].freeze
        group_select = %w[orders.id order_items.order_id].freeze

        filtered_count = current_user.orders.size
        records = current_user.orders
                              .left_joins(:order_items)
                              .order(sort_name => sort_dir)
                              .select(column_select)
                              .group(group_select)
                              .limit(requested_length)
                              .offset(requested_start)

        ActiveRecord::Base.include_root_in_json = false

        data = []

        records.each do |record|
          hash = record.as_json
          hash['total_price'] = record.total_price.format unless record.total_price_cents.nil? || record.total_price_currency.nil?

          data << hash
        end

        payload = {
          draw: params[:draw],
          recordsTotal: current_user.orders.size,
          recordsFiltered: filtered_count,
          data:
        }

        render json: payload, status: :ok
      end

      private

      def find_order
        @order = current_user.orders.find_by(id: params[:id])
        render 'error/not_found', status: :not_found, layout: 'error' unless @order
      end
    end
  end
end

app/controllers/app/user_space_controller.rb
# frozen_string_literal: true

module App
  class UserSpaceController < AppController
  end
end

app/helpers/app/market_space/order_helper.rb
module App::MarketSpace::OrderHelper
end

app/helpers/app/user_space/order_helper.rb
module App::UserSpace::OrderHelper
end

app/helpers/app/user_space_helper.rb
module App::UserSpaceHelper
end

app/views/app/user_space/order/index.html.erb
<!-- displays a datatable of orders -->

<% content_for :title, 'Your Orders' %>

<div class="content-header d-flex mb-1 justify-content-between">
  <h1 class="m-0" style="line-height: 39px;">
    Your Orders
  </h1>
</div>
<div class="content-body">

  <section id="products-index">

    <div class="card">
      <div class="card-content">
        <div class="card-body">

          <table id="orders-table" class="table table-striped" style="width:100%"
                 data-controller="app--user-space--order--index"
                 data-app--user-space--order--index-url-value="<%= app_user_space_order_datatable_path %>"
                 data-app--user-space--order--index-item-path-value="<%= app_user_space_order_index_path %>"
          >
            <thead>
              <tr>
                <th>Date</th>
                <th>Num of Products</th>
                <th>Order Status</th>
                <th>Total Price</th>
                <th>View</th>
              </tr>
            </thead>

            <tbody class="table-striped"></tbody>

            <tfoot>
              <tr>
                <th>Date</th>
                <th>Num of Products</th>
                <th>Order Status</th>
                <th>Total Price</th>
                <th>View</th>
              </tr>
            </tfoot>
          </table>

        </div>
      </div>
    </div>

  </section>

</div>

app/views/app/user_space/order/show.html+turbo_frame.erb
<%= turbo_frame_tag @order do %>

  <div class="d-flex justify-content-between mb-2">

    <div>
      <h1 class="m-0" style="line-height: 39px;">
        Order
      </h1>
      <small class="text-muted">
        <%= @order.id %>
      </small>
    </div>

    <div>

    </div>

  </div>


  <div class="card">
    <div class="card-content">
      <div class="card-body">

        <div class="row">

          <div class="col-12 col-lg-6 col-md-6 col-sm-12">
            <div class="card">
              <div class="card-body">
                <h1 class="card-title mb-0">
                  Details
                </h1>
                <hr>
                <br>
                <div class="row">

                  <div class="col-12">
                    <h5 class="h5">
                      <%= @order.total_price.format %> <%= @order.total_price_currency %>
                    </h5>
                    <p>
                      <br>
                    </p>
                  </div>

                  <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <h5 class="mb-1">
                      <i data-feather='info' class="m2-25"></i> Information
                    </h5>
                    <!-- created at -->
                    <p>
                      <b>Created at:</b> <%= @order.created_at %>
                    </p>
                    <!-- updated at -->
                    <p>
                      <b>Updated at:</b> <%= @order.updated_at %>
                    </p>

                    <!-- status -->
                    <p>
                      <b>Status:</b> <%= render App::OrderStatusComponent.new(@order.status), cached: true %>
                    </p>
                  </div>

                  <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <h5 class="mb-1">
                      <i data-feather="map-pin" class="me-25"></i>Address
                    </h5>

                    <!-- order address -->
                    <p>
                      <b>Name:</b> <%= @order.shipping_name %>
                    </p>

                    <p>
                      <b>Address Line 1:</b> <%= @order.address_line_1 %>
                    </p>

                    <% unless @order.address_line_2.blank? %>
                      <p>
                        <b>Address Line 2:</b> <%= @order.address_line_2 %>
                      </p>
                    <% end %>

                    <p>
                      <b>City:</b> <%= @order.city %>
                    </p>

                    <p>
                      <b>State:</b> <%= @order.state %>
                    </p>

                    <p>
                      <b>Zip:</b> <%= @order.zip %>
                    </p>

                    <p>
                      <b>Country:</b> <%= @order.country %>
                    </p>

                  </div>

                </div>

              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header">
      <h4 class="card-title">Items</h4>
    </div>
    <div class="card-body">
      <p class="card-text">

      </p>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>Product</th>
          <th>Quantity</th>
        </tr>
        </thead>
        <tbody>

        <% @order.order_items.each do |order_item| %>
          <tr>
            <td>
              <a href="<%= product_path order_item.product %>" target="_blank">
                <i data-feather="external-link"></i> <%= order_item.product.name %>
              </a>
            </td>
            <td>
              <%= order_item.quantity %>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>

<% end %>

app/views/app/user_space/order/show.html.erb
<% content_for :title, "Order #{@order.id}" %>

<%= turbo_frame_tag @order, src: app_user_space_order_path(@order), loading: :lazy do %>
  <%= render SpinnerComponent.new, cached: true %>
<% end %>